### ISSUE TITLE
Abandoned or waiting?

### ISSUE THREAD

**Issue by drkibitz** [CreateJS/EaselJS-NodeJS#1]
Was just wondering if this is sitting here waiting to be committed to, or will it eventually be deleted?

**Comment by gskinner** [comment]
Not abandoned per se. We'd love to have community involvement on helping to keep it up to date, so we can maintain our focus on the core libraries.

**Comment by wdamien** [comment]
You can find the source here -> https://github.com/wdamien/node-easel/. I try to keep it up-to date to match the releases of Easel, but it's a side project for me so theres not a ton of active development occurring.
